# [BB] SDF atlas generator -- TTF outline in, distance-field atlas + metrics out.
#
# Runs offline. The engine never sees a TTF; it loads the PNG this writes like
# any other texture and reads the metrics beside it.
#
# The field comes from the glyph OUTLINE (GraphicsPath), not from a rasterised
# bitmap of one, so the only resolution limit is the supersample factor rather
# than anything baked into a lump.
#
# All the work is in the C# below, deliberately: a PowerShell loop over a
# million pixels is minutes, the same loop in C# is under a second.

param(
  [string]$Ttf    = 'C:\Users\Command\Desktop\freearcadefonts\PixeloidMono.ttf',
  [string]$OutDir = 'C:\Users\Command\AppData\Local\Temp\claude\E--UZDXREMA\76030631-3473-4c10-9592-9a316966da8b\scratchpad\sdfout',
  [int]$Cell      = 64,
  [int]$Spread    = 8,
  [int]$Super     = 8
)

Add-Type -AssemblyName System.Drawing

$src = @'
using System;
using System.Drawing;
using System.Drawing.Drawing2D;
using System.Drawing.Imaging;
using System.Drawing.Text;
using System.Runtime.InteropServices;
using System.Text;

public class SdfGen
{
  // 8SSEDT -- two sweeps, each pixel inheriting the best offset its already
  // finished neighbours found. O(n), where brute force is O(n * spread^2).
  // At 8x supersampling that is the difference between a second and a wait.
  struct Pt { public int dx, dy; public int D { get { return dx*dx + dy*dy; } } }

  // MUST stay small enough that INF*INF fits in an int. 1<<28 does not:
  // 2^56 wraps to exactly 0, so every unseeded point reported distance zero,
  // no comparison ever won, and the transform silently did nothing -- the
  // whole atlas came out flat 128 grey. 1<<14 squared is 2.7e8, comfortably
  // inside int, and still far beyond any real distance in a 512px cell.
  const int INF = 1 << 14;

  static Pt Get(Pt[] g, int w, int h, int x, int y)
  {
    if (x < 0 || y < 0 || x >= w || y >= h) { Pt e; e.dx = INF; e.dy = INF; return e; }
    return g[y*w + x];
  }
  static void Cmp(Pt[] g, int w, int h, ref Pt p, int x, int y, int ox, int oy)
  {
    Pt o = Get(g, w, h, x+ox, y+oy);
    if (o.dx >= INF) return;
    o.dx += ox; o.dy += oy;
    if (o.D < p.D) p = o;
  }
  static void Sweep(Pt[] g, int w, int h)
  {
    for (int y = 0; y < h; y++) {
      for (int x = 0; x < w; x++) { Pt p = g[y*w+x];
        Cmp(g,w,h,ref p,x,y,-1,0); Cmp(g,w,h,ref p,x,y,0,-1);
        Cmp(g,w,h,ref p,x,y,-1,-1); Cmp(g,w,h,ref p,x,y,1,-1); g[y*w+x]=p; }
      for (int x = w-1; x >= 0; x--) { Pt p = g[y*w+x];
        Cmp(g,w,h,ref p,x,y,1,0); g[y*w+x]=p; }
    }
    for (int y = h-1; y >= 0; y--) {
      for (int x = w-1; x >= 0; x--) { Pt p = g[y*w+x];
        Cmp(g,w,h,ref p,x,y,1,0); Cmp(g,w,h,ref p,x,y,0,1);
        Cmp(g,w,h,ref p,x,y,-1,1); Cmp(g,w,h,ref p,x,y,1,1); g[y*w+x]=p; }
      for (int x = 0; x < w; x++) { Pt p = g[y*w+x];
        Cmp(g,w,h,ref p,x,y,-1,0); g[y*w+x]=p; }
    }
  }
  static float[] Field(bool[] mask, int w, int h)
  {
    Pt[] ins = new Pt[w*h], outs = new Pt[w*h];
    Pt zero; zero.dx = 0; zero.dy = 0;
    Pt inf;  inf.dx = INF; inf.dy = INF;
    for (int i = 0; i < w*h; i++) { ins[i] = mask[i] ? zero : inf; outs[i] = mask[i] ? inf : zero; }
    Sweep(ins, w, h); Sweep(outs, w, h);
    float[] d = new float[w*h];
    for (int i = 0; i < w*h; i++) {
      double a = ins[i].dx  >= INF ? 0 : Math.Sqrt(ins[i].D);
      double b = outs[i].dx >= INF ? 0 : Math.Sqrt(outs[i].D);
      d[i] = (float)(b - a);      // inside positive
    }
    return d;
  }

  // Whole job: every glyph, packed, written, metrics returned.
  public static string Build(string ttf, string outDir, int cell, int spread, int super)
  {
    PrivateFontCollection pfc = new PrivateFontCollection();
    pfc.AddFontFile(ttf);
    FontFamily fam = pfc.Families[0];

    int first = 32, last = 126;
    int count = last - first + 1;
    int cols = 16;
    int rows = (count + cols - 1) / cols;
    int aw = cols * cell, ah = rows * cell;

    // Fit the em box inside the cell minus both spread margins, so the field
    // has somewhere to fall off on every side. A glyph drawn edge to edge has
    // no outside to measure against and its glow would stop dead at the seam.
    float emPx = (cell - 2*spread);

    // Opaque black everywhere to start: 0 means "far outside the glyph", which
    // is the right answer for a cell no glyph ever writes to. Left at the
    // default the padding cell reads alpha 0 and the space glyph reads mid
    // grey -- i.e. exactly on the edge -- and both would draw a phantom.
    byte[] atlas = new byte[aw * ah * 4];
    for (int i = 0; i < aw * ah; i++) atlas[i*4 + 3] = 255;
    StringBuilder mt = new StringBuilder();
    mt.AppendLine("# SDF font metrics -- generated by mksdf.ps1, do not edit");
    mt.AppendLine("font " + fam.Name);
    mt.AppendLine("cell " + cell);
    mt.AppendLine("spread " + spread);
    mt.AppendLine("em " + emPx.ToString(System.Globalization.CultureInfo.InvariantCulture));
    mt.AppendLine("atlas " + aw + " " + ah);

    int S = cell * super;
    StringFormat sf = (StringFormat)StringFormat.GenericTypographic.Clone();
    sf.FormatFlags |= StringFormatFlags.MeasureTrailingSpaces;

    using (Bitmap bm = new Bitmap(S, S, PixelFormat.Format32bppArgb))
    using (Graphics g = Graphics.FromImage(bm))
    {
      // Reference advance from a font-wide measure, so a monospace font keeps
      // its uniform pitch even for glyphs whose ink is narrow. Measuring ink
      // per glyph would make a '1' advance less than a '0' and break exactly
      // the tabular alignment a mono font was chosen for.
      float refAdv;
      using (Font probe = new Font(fam, emPx, FontStyle.Regular, GraphicsUnit.Pixel))
        refAdv = g.MeasureString("0", probe, PointF.Empty, sf).Width;

      for (int ci = 0; ci < count; ci++)
      {
        char ch = (char)(first + ci);
        g.Clear(Color.Black);
        g.SmoothingMode = SmoothingMode.None;
        g.PixelOffsetMode = PixelOffsetMode.Half;

        using (GraphicsPath gp = new GraphicsPath())
        {
          if (ch != ' ')
          {
            gp.AddString(ch.ToString(), fam, 0, emPx * super,
                         new PointF(spread * super, spread * super), sf);
            if (gp.PointCount > 0) g.FillPath(Brushes.White, gp);
          }
        }

        BitmapData bd = bm.LockBits(new Rectangle(0,0,S,S), ImageLockMode.ReadOnly, PixelFormat.Format32bppArgb);
        byte[] raw = new byte[bd.Stride * S];
        Marshal.Copy(bd.Scan0, raw, 0, raw.Length);
        bm.UnlockBits(bd);

        bool[] mask = new bool[S*S];
        bool anyInk = false;
        for (int y = 0; y < S; y++)
          for (int x = 0; x < S; x++)
            if (raw[y*bd.Stride + x*4 + 1] > 127) { mask[y*S + x] = true; anyInk = true; }

        int gx = (ci % cols) * cell, gy = (ci / cols) * cell;

        // A glyph with no ink -- space, and any codepoint the font omits --
        // has no edge to measure from, so the transform returns 0 everywhere
        // and 0 encodes to mid grey, which the shader reads as sitting exactly
        // ON the edge. It would draw a solid block. Say "far outside" instead.
        if (!anyInk)
        {
          mt.AppendLine(string.Format(System.Globalization.CultureInfo.InvariantCulture,
            "g {0} {1} {2} {3} {4} {5:0.###}", (int)ch, gx, gy, cell, cell, refAdv));
          continue;
        }

        float[] fld = Field(mask, S, S);
        for (int cy = 0; cy < cell; cy++)
        for (int cx = 0; cx < cell; cx++)
        {
          double acc = 0;
          for (int sy = 0; sy < super; sy++)
            for (int sx = 0; sx < super; sx++)
              acc += fld[(cy*super+sy)*S + (cx*super+sx)];
          double dCell = (acc / (super*super)) / super;   // mask px -> cell px
          double n = 0.5 + dCell / (2.0 * spread);        // -> 0..1, 0.5 = edge
          byte v = (byte)Math.Max(0, Math.Min(255, Math.Round(n * 255)));
          int o = ((gy + cy) * aw + (gx + cx)) * 4;
          atlas[o+0] = v; atlas[o+1] = v; atlas[o+2] = v; atlas[o+3] = 255;
        }

        mt.AppendLine(string.Format(System.Globalization.CultureInfo.InvariantCulture,
          "g {0} {1} {2} {3} {4} {5:0.###}", (int)ch, gx, gy, cell, cell, refAdv));
      }
    }

    using (Bitmap ab = new Bitmap(aw, ah, PixelFormat.Format32bppArgb))
    {
      BitmapData bd = ab.LockBits(new Rectangle(0,0,aw,ah), ImageLockMode.WriteOnly, PixelFormat.Format32bppArgb);
      for (int y = 0; y < ah; y++)
        Marshal.Copy(atlas, y*aw*4, (IntPtr)(bd.Scan0.ToInt64() + y*bd.Stride), aw*4);
      ab.UnlockBits(bd);
      ab.Save(System.IO.Path.Combine(outDir, "sdfatlas.png"), ImageFormat.Png);
    }
    System.IO.File.WriteAllText(System.IO.Path.Combine(outDir, "sdfmetrics.txt"), mt.ToString());
    return fam.Name + " | " + aw + "x" + ah + " | " + count + " glyphs";
  }
}
'@

if (-not ([System.Management.Automation.PSTypeName]'SdfGen').Type) {
  Add-Type -TypeDefinition $src -ReferencedAssemblies 'System.Drawing.dll'
}

New-Item -ItemType Directory -Force -Path $OutDir | Out-Null
$r = [SdfGen]::Build($Ttf, $OutDir, $Cell, $Spread, $Super)
Write-Output "built: $r"
Write-Output "out:   $OutDir"
